<?php

namespace QuizBundle\Repository;

use Doctrine\DBAL\Connection;
use PDO;
use QuizBundle\Entity\Question;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRandom(Connection $connection, $num){

        $stm = $connection->prepare("SELECT id FROM questions ORDER BY rand() LIMIT $num");
        $stm->execute([]);
           return $stm->fetchAll(PDO::FETCH_COLUMN);
    }
}
