<?php

namespace QuizBundle\Repository;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use PDO;
use QuizBundle\Entity\Question;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Question::class));
    }
    public function getRandom(Connection $connection, $num){
        $num = intval($num);
        $stm = $connection->prepare("SELECT id FROM questions ORDER BY rand() LIMIT :num");
        $stm->bindParam(':num',$num, PDO::PARAM_INT);
        $stm->execute();
           return $stm->fetchAll(PDO::FETCH_COLUMN);
    }
    public function saveQuestion(Question $question){
        $this->_em->persist($question);
        $this->_em->flush();
    }
    public function deleteQuestion(Question $question){
        $this->_em->remove($question);
        $this->_em->flush();
    }
}
