<?php

namespace QuizBundle\Repository;

use QuizBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllUsers()
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select(User::class)
            ->from('User', 'u')
            ->where('u.id = ?1')
            ->orderBy('u.name', 'ASC');




        return $qb->getQuery()
            ->getResult();
    }
}
